execute pathogen#infect() 
map <silent> <C-n> :NERDTreeFocus<CR>

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%100v.\+/

hi Search cterm=bold ctermfg=white ctermbg=23

syntax enable

set wrap!

set smartindent
set cindent
set cinkeys-=0#
set indentkeys-=0#

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set number
set ai
set si

